version: "3"

services:
  api:
    container_name: api
    build: .
    depends_on:
      - caddy
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules

  caddy:
    container_name: caddy
    image: caddy:2.7.4-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app

volumes:
  caddy_data:
  caddy_config:
