name: Deploy

on:
  push:
    branches: ["main", "master"]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      
      - name: Install Dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Start Script
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.IP_ADDR }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            scp -r dist ${{ format('{0}@{1}', secrets.USERNAME, secrets.IP_ADDR) }}:~/nodejsapp
            