name: Deploy

on:
  push:
    branches: ["main", "master"]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        run: HUSKY=0 npm ci

      - name: Build
        run: npm run build

      - name: Copy Build to Server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.IP_ADDR }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "dist,package.json,package-lock.json"
          target: ~/nodejsapp/deployed

      - name: Start Script
        uses: appleboy/ssh-action@v1.0.0
        env:
          APP_NAME: "TheApp"
        with:
          host: ${{ secrets.IP_ADDR }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script_stop: true # stop after first failure
          script: |
            cd ~/nodejsapp/deployed
            npm i npe
            npx npe scripts.prepare ""
            npm ci --omit=dev

            PM2_EXIST=$(if pm2 list 2> /dev/null | grep -q $APP_NAME; then echo "Yes" ; else echo "No" ; fi)
            
            if [ $PM2_EXIST = Yes ] ; then
                pm2 restart $APP_NAME
                echo "Restart $APP_NAME."
            else
                pm2 start ~/nodejsapp/deployed/dist/index.js --name=$APP_NAME
                echo "Start $APP_NAME."
            fi

