name: Run Job

on:
  pull_request:
    branches-ignore: ["main", "master"]
  push:
    branches-ignore: ["main", "master"]

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        run: npm i

      - name: Check Format
        run: prettier . --check

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
